add validate branch check

diff --git a/.github/workflows/emulate-cdk-deploy.yml b/.github/workflows/emulate-cdk-deploy.yml
--- a/.github/workflows/emulate-cdk-deploy.yml
+++ b/.github/workflows/emulate-cdk-deploy.yml
@@ -23,6 +23,11 @@ jobs:
     env:
       ENVIRONMENT: ${{ github.event.inputs.targetEnvironment != '' && github.event.inputs.targetEnvironment || (startsWith(github.ref, 'refs/tags/') && 'live' || 'stage' )}}
     steps:
+      - name: Validate branch
+        if: github.event.release.target_commitish != 'main' && startsWith(github.ref, 'refs/tags/')
+        run: |
+          echo "Error trying to deploy on live a non-master branch."
+          exit 1
       - name: Configure AWS credentials
         run: |
           echo ${{ secrets[format('{0}_AWS_ACCESS_KEY_ID', env.ENVIRONMENT)] }}
